# Generated by Django 3.1.4 on 2021-02-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('T', 'Tv'), ('C', 'Cloth')], max_length=10),
        ),
    ]
